---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "rna4"
  namespace: "rna4"
spec:
  baseDomain: "cloud.lab.eng.bos.redhat.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.10.16-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC++ImKBMk4tTEA4nX31MPjwtUm5ZfExosNQPXGVWlWlsugQdXhQi79Q72w8177kv8IcQeT97uJIvhN5TiTVKfnz/DRu3wdlXhXojFUmc3PLkk+DHRbg+ddCIKdiLu13Q0EJaQFaH6g0WD/NNkfsiZoS8stF4x3+FBMJxbVw3jTMy30+kAXTn58dm1EPsKGABlo24b6b1+FpME+Xvi3/5FF+XsApC24lIvILims/4axNJRbiXU4v8VebqxcqwGeonf9dJFLnoplELEiXNcHx4F5KZeqyieRkjywdGQEg8IV0B8Qt+mE4+57UG1c4/cxjAoWPItro0jaPv0etPqo7+bEQx7bNRL054bYQDGIf5yDz7yp+RkzAQhY48plHtmMvfPOnJbz/8eSwPAGMx2aNsCPTuuDeaGVyMhKw5jPxVQWgc9xBPTXabFBJ8r794rxpZqYKFEIXA3HF7FlBtN9gIP4EJ728UTKIRm99oh40pzp58WdLASILQbCPB7i2nf5vGk= core@metal3"
  clusters:
    - clusterName: "rna4"
      clusterLabels:
        group-vdu: ""
        common-49: true
        sites : "rna4"
      networkType: "OVNKubernetes"
      clusterNetwork:
        - cidr: "10.128.0.0/14"
          hostPrefix: 23
      serviceNetwork:
        - "172.30.0.0/16"
      machineNetwork:
        - cidr: "10.19.6.0/24"
      additionalNTPSources:
        - 10.18.100.10
      nodes:
        - hostName: "metal1"
          role: master
          bmcAddress: "redfish-virtualmedia://10.19.143.120/redfish/v1/Systems/System.Embedded.1/"
          bmcCredentialsName:
            name: "bmh-secret"
          bootMACAddress: "B8:59:9F:B1:11:C5"
          bootMode: "UEFI"
          rootDeviceHints:
            deviceName: "/dev/nvme0n1"
          cpuset: "0-1,30-33,62-63"
          nodeNetwork:
            config:
              interfaces:
                - name: eno2
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: true
                    address:
                      - ip: 10.19.6.20
                        prefix-length: 24
                  ipv6:
                    enabled: false
                - name: eno1
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: true
                    address:
                      - ip: 10.10.10.10
                        prefix-length: 32
                  ipv6:
                    enabled: false
              dns-resolver:
                config:
                  search:
                    - 10.19.6.21
              routes:
                config:
                  - destination: 0.0.0.0/0
                    next-hop-interface: eno2
                    next-hop-address: 10.19.6.254
            interfaces:
              - name: "eno2"
                macAddress: "B8:59:9F:B1:11:C5"
              - name: "eno1"
                macAddress: "B8:59:9F:B1:11:C4"
