---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "rna4"
  namespace: "rna4"
spec:
  baseDomain: "cloud.lab.eng.bos.redhat.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.10.16-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCm8aBT4vr7PRBv0P33lCbCWNo6tA6DsqdjgfezoVzIp1L47LQhQEqg3/zh6cj4V8tAl3HXVZM3VfUQOHKyUC0FyJ5AQqCDhwe6mi/WzSgECs1TbjkO67pQN0udC22M3PnTNmjS/hDIJ0VDFZk65WVTIMZOExVzhZyyWZdCoSami/etLC7Q6PkjUsH/vmfCDaDFuUj8ZlzaSIR/BxOkaGWHd6UWrlqr0yHiWpZ1zcHqdXr3nSA415+g79a5hWjM7sdXe3xIfxy8xarK1KyyiYK8n3V0mfrDhn0IqLgYldbniBOF8dvYA3n9iF0mnzc+ClZnAz8ZF3KjgkafZFt4ApeRSNEilHoAssPfdpUv5hWajPP/PiGvvgiFU3FsjRdX88q9xtRF4ymjxh6cplqHtdM0W5Uu5YEYModQGafTAORWw0DxD6x2MozURnJ1DQsrQVRdu4KMN2wvZY1REampsqrvP4GrAIjL6OhSX8QfGX3QtBV/YLfbRJenVIE9T0DccL8= core@metal3"
  clusters:
    - clusterName: "rna4"
      clusterLabels:
        group-vdu: ""
        common-49: true
        sites : "rna4"
      networkType: "OVNKubernetes"
      clusterNetwork:
        - cidr: "10.128.0.0/14"
          hostPrefix: 23
      serviceNetwork:
        - "172.30.0.0/16"
      machineNetwork:
        - cidr: "10.19.6.0/24"
      additionalNTPSources:
        - 10.18.100.10
      nodes:
        - hostName: "metal1"
          role: master
          bmcAddress: "redfish-virtualmedia://10.19.143.120/redfish/v1/Systems/System.Embedded.1/"
          bmcCredentialsName:
            name: "bmh-secret"
          bootMACAddress: "B8:59:9F:B1:11:C5"
          bootMode: "UEFI"
          rootDeviceHints:
            deviceName: "/dev/nvme0n1"
          cpuset: "0-1,30-33,62-63"
          nodeNetwork:
            config:
              interfaces:
                - name: eno2
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: true
                    address:
                      - ip: 10.19.6.21
                        prefix-length: 24
                  ipv6:
                    enabled: false
              dns-resolver:
                config:
                  search:
                    - 10.19.6.21
              routes:
                config:
                  - destination: 0.0.0.0/0
                    next-hop-interface: eno2
                    next-hop-address: 10.19.6.254
            interfaces:
              - name: "eno2"
                macAddress: "B8:59:9F:B1:11:C5"
