---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "rna4"
  namespace: "rna4"
spec:
  baseDomain: "cloud.lab.eng.bos.redhat.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.10.16-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDS7y5bAwNck1Tg9YPh441p7Zxgb4oqptSp2vmVqsqqb2ut3T1PQ3ey7WOygK0BNfIbWhESdp9CuHxTI0VqdmthFinfBf+Q+yua+ZlKlMx1uj6WQp7DzmKXbxU0am7WsIwFQWj3st6AxOlTYPH+2czYkqjebYc2yhrrAM8b6WHV65iKzSfMKM+ZALlFyUeLbOAXwkEHQ6TaIJUktXBoP5s3uaFk9C8AUoU+qwIe2xoTs9folY6DOV3DQIB2856VQ6/nTmS2Q+Mt7rWGXKD4mp4lmXCFHsnRvYsCO8GnzQhZo0SHDUcVSprVax+OGLFt+8Fn/hgrh7C+dBvWjtTmKsbf0b7gCbG7u5wBeN8VVXPiJvAWAQ46/ytEJEtV7taOFXLo+vKsaFeW/grRgVA++EWierDSYjm3mnL1nNVvBCaJOmOSArYPj1C1VRXUt+kNzWEUr5kyXBnIdWoC5WfhCFZQfPdptvwplOXMgao+kMiFoG9d3g1jWxACSUopcjr58cc= core@metal3"
  clusters:
    - clusterName: "rna4"
      clusterLabels:
        group-vdu: ""
        common-49: true
        sites : "rna4"
      networkType: "OVNKubernetes"
      clusterNetwork:
        - cidr: "10.128.0.0/14"
          hostPrefix: 23
      serviceNetwork:
        - "172.30.0.0/16"
      machineNetwork:
        - cidr: "10.19.6.0/24"
      additionalNTPSources:
        - 10.18.100.10
      nodes:
        - hostName: "metal1"
          role: master
          bmcAddress: "redfish-virtualmedia://10.19.143.120/redfish/v1/Systems/System.Embedded.1/"
          bmcCredentialsName:
            name: "bmh-secret"
          bootMACAddress: "B8:59:9F:B1:11:C5"
          bootMode: "UEFI"
          rootDeviceHints:
            deviceName: "/dev/nvme0n1"
          cpuset: "0-1,30-33,62-63"
          nodeNetwork:
            config:
              interfaces:
                - name: eno2
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: true
                    address:
                      - ip: 10.19.6.20
                        prefix-length: 24
                  ipv6:
                    enabled: false
                - name: eno1
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: true
                    address:
                      - ip: 10.10.10.10
                        prefix-length: 32
                  ipv6:
                    enabled: false
              dns-resolver:
                config:
                  search:
                    - 10.19.6.21
              routes:
                config:
                  - destination: 0.0.0.0/0
                    next-hop-interface: eno2
                    next-hop-address: 10.19.6.254
            interfaces:
              - name: "eno2"
                macAddress: "B8:59:9F:B1:11:C5"
              - name: "eno1"
                macAddress: "B8:59:9F:B1:11:C4"
