---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "rna4"
  namespace: "rna4"
spec:
  baseDomain: "cloud.lab.eng.bos.redhat.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.10.16-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6iRPHKc0CTxGa+v2ueT4yx0BUrVXLPS0lt51XNxCeUaWWI6n9BKygdIWkeA4bGjxT/0G83ZRtuAX+3l8oDyi/Qtk/2jxw6GZrC0nYpKWv/NhE21FwRXGudQ0f2JQSaySFsApv2A9RKqxvqwjriA4ZzSeHmmd8jNT/ZbDNGwXaYlwycpze+ybm6YUCVE9obZgpS7wpcPGGFHj0eNs2YW47yUBB9jfT9zi4iXUQJwPmXGZmgSqFbDJC+uaV2Ru1N1c7a/TYlvaNEJEfQEZdyhUERN26NaXxS0k+4kkfCMwGMhy+WBkRrl+FGm5ThExZum1XVUwG8d1uSOarQ3P1bYIdSpaOv2rhnuLRQ8Kkop8GMMxpaAaNBu3bfpJM77kVo/DMLbU5NnhMOK8KAcSlRJ6YqX+ySSXA1X7HB6XCMIRCUnq1pYw6BN95uATg8IjfkvJ6CUEE57DkkFf/Ed483uKUEWTx96lPmltPYNMUTTJMgZvfro7M9Vzzpvi/aYmppnc= core@metal3"
  clusters:
    - clusterName: "rna4"
      clusterLabels:
        group-vdu: ""
        common-49: true
        sites : "rna4"
      networkType: "OVNKubernetes"
      clusterNetwork:
        - cidr: "10.128.0.0/14"
          hostPrefix: 23
      serviceNetwork:
        - "172.30.0.0/16"
      machineNetwork:
        - cidr: "10.19.6.0/24"
      additionalNTPSources:
        - 10.18.100.10
      nodes:
        - hostName: "metal1"
          role: master
          bmcAddress: "redfish-virtualmedia://10.19.143.120/redfish/v1/Systems/System.Embedded.1/"
          bmcCredentialsName:
            name: "bmh-secret"
          bootMACAddress: "B8:59:9F:B1:11:C5"
          bootMode: "UEFI"
          rootDeviceHints:
            deviceName: "/dev/nvme0n1"
          cpuset: "0-1,30-33,62-63"
          nodeNetwork:
            config:
              interfaces:
                - name: eno2
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: true
                    address:
                      - ip: 10.19.6.20
                        prefix-length: 24
                  ipv6:
                    enabled: false   
                - name: eno1
                  type: ethernet
                  state: up
                  ipv4:
                    address:
                    - ip: 10.10.10.10
                      prefix-length: 24
                    enabled: true   
                  ipv6:
                    enabled: false
              dns-resolver:
                config:
                  search:
                    - 10.19.6.21
              routes:
                config:
                  - destination: 0.0.0.0/0
                    next-hop-interface: eno2
                    next-hop-address: 10.19.6.254
            interfaces:
              - name: "eno2"
                macAddress: "B8:59:9F:B1:11:C5"
              - name: "eno1"
                macAddress: "B8:59:9F:B1:11:C4"
