---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "rna4"
  namespace: "rna4"
spec:
  baseDomain: "cloud.lab.eng.bos.redhat.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.10.16-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCyBYW2ZeOz/dWsComLuQyqpK3YduK+PwBwbPESWK+tZTrTdBW51HieubzO5osJuk7QhaHPmuTKu45qWRNfGTPaxvIs6N2MeiTym5OnosV6eVubnuopO+ajmnZQmnmdr/TlhZt+x0NuGSFv4BEd/KasorHuBdI0V8aQOrz3hH6dfF5+VfAvVk9tMNbyYWVffvAGE0nbjwz/a44S/12p/isAJu6GB89q5Pmp2CiKU+v4+O+Do6yB3gAePi9juKVCtOEl8OES+tMw4k+FbiS7Czwm1GH9xAJ3e9rZbSdOXlR5NE0a5EGBoybQ9ex1WEwfQLzWIkHhdpm5nJlm4BWcvUJha/kfYldUxwFLwHkALKxaNOD16NrFzBpTeh5TPSf0shHfyJiSNADLkF6LJ5j21P/EOCXEscwV49p4W4GGRC92zqRzrAfr3k8yau0iJXJ+iQNE0J/MWrcsZpiiaeaKzbtcpIIfUQMWBHMVlwuNorDX5Z1+CYZwhQLa4LPs1N31HF0= core@metal3"
  clusters:
    - clusterName: "rna4"
      clusterLabels:
        group-vdu: ""
        common-49: true
        sites : "rna4"
      networkType: "OVNKubernetes"
      clusterNetwork:
        - cidr: "10.128.0.0/14"
          hostPrefix: 23
      serviceNetwork:
        - "172.30.0.0/16"
      machineNetwork:
        - cidr: "10.19.6.0/24"
      additionalNTPSources:
        - 10.18.100.10
      nodes:
        - hostName: "metal1"
          role: master
          bmcAddress: "redfish-virtualmedia://10.19.143.120/redfish/v1/Systems/System.Embedded.1/"
          bmcCredentialsName:
            name: "bmh-secret"
          bootMACAddress: "B8:59:9F:B1:11:C5"
          bootMode: "UEFI"
          rootDeviceHints:
            deviceName: "/dev/nvme0n1"
          cpuset: "0-1,30-33,62-63"
          nodeNetwork:
            config:
              interfaces:
                - name: eno2
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: true
                    address:
                      - ip: 10.19.6.21
                        prefix-length: 24
                  ipv6:
                    enabled: false   
                - name: eno1
                  type: ethernet
                  state: up
                  ipv4:
                    address:
                    - ip: 10.10.10.10
                      prefix-length: 24
                    enabled: true   
                  ipv6:
                    enabled: false
              dns-resolver:
                config:
                  search:
                    - 10.19.6.21
              routes:
                config:
                  - destination: 0.0.0.0/0
                    next-hop-interface: eno2
                    next-hop-address: 10.19.6.254
            interfaces:
              - name: "eno2"
                macAddress: "B8:59:9F:B1:11:C5"
              - name: "eno2"
                macAddress: "B8:59:9F:B1:11:C4"
