---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "rna4"
  namespace: "rna4"
spec:
  baseDomain: "cloud.lab.eng.bos.redhat.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.10.16-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDa2cQk1RSe2HRjlx0aQpaUGzxBjSmLv6ccIzOVM8r4uYfQgTqLE1NE/27L/8EGUCQqddt1q6SsTH1A/YPRbCOKEEJFsj33GuJul7whVA9Jce3nDBdnZVoi86GgSw9+EKWx7o20kAiyVv1CWY6CxcJMnBsMekyI3Er/LBdFzv0EXYFLTPbOi+0TIROu3XvnucNi7GDzd7zo8cMW+Wy+/8TnNXgXnngdd7ESNsW1hWA2ZLaUvUvETUaaSNBN8qTgpYEKbPQ2yGwPCmsozr5mT/d60uTjRXilreClc8V0bOd8eUvCo4gDXAOpPhXRTeg66yH6axPooQjHrD8OJGraSuzJnIKJQzmx+VDNPaHxDiLuapqqnh0FeIbYD3GTV4FH1nR7z0/Xq6TcH0OL3NyVCVHtTJ5ZB3NNbRPMrxkh0KNMSzxU0QgIjCJspLnO1VowScCb6bPJlxShBz+D5dffCef3MisvD9DY3ssX0YB6jD8gGHFz6qGioNpgZ/XW7m/xZME= core@metal3"
  clusters:
    - clusterName: "rna4"
      clusterLabels:
        group-vdu: ""
        common-49: true
        sites : "rna4"
      networkType: "OVNKubernetes"
      clusterNetwork:
        - cidr: "10.128.0.0/14"
          hostPrefix: 23
      serviceNetwork:
        - "172.30.0.0/16"
      machineNetwork:
        - cidr: "10.19.6.0/24"
      additionalNTPSources:
        - 10.18.100.10
      nodes:
        - hostName: "metal1"
          role: master
          bmcAddress: "redfish-virtualmedia://10.19.143.120/redfish/v1/Systems/System.Embedded.1/"
          bmcCredentialsName:
            name: "bmh-secret"
          bootMACAddress: "B8:59:9F:B1:11:C5"
          bootMode: "UEFI"
          rootDeviceHints:
            deviceName: "/dev/nvme0n1"
          cpuset: "0-1,30-33,62-63"
          nodeNetwork:
            config:
              interfaces:
                - name: eno2
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: true
                    address:
                      - ip: 10.19.6.20
                        prefix-length: 24
                  ipv6:
                    enabled: false   
                - name: eno1
                  type: ethernet
                  state: up
                  ipv4:
                    address:
                    - ip: 10.10.10.10
                      prefix-length: 24
                    enabled: true   
                  ipv6:
                    enabled: false
              dns-resolver:
                config:
                  search:
                    - 10.19.6.21
              routes:
                config:
                  - destination: 0.0.0.0/0
                    next-hop-interface: eno2
                    next-hop-address: 10.19.6.254
            interfaces:
              - name: "eno2"
                macAddress: "B8:59:9F:B1:11:C5"
              - name: "eno1"
                macAddress: "B8:59:9F:B1:11:C4"
