apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ns.yaml
- common/common-du-vseextras.yaml
- common/common-du-vseextras
generators:
# This is common to all RAN deployments
- common/common-prega416.yaml
#- common/common-prega416extras.yaml
#- common/common-du-vse414.yaml
- common/common-du-vseextras

## This group policy is for all single-node deployments:
#- group/vdu.yaml
## This group validator policy is for all single-node deployments:
#- site/rna4.yaml
## These are examples that should be replicated for every individual site:
#- cluster/rna4.yaml


