apiVersion: v1
kind: Namespace
metadata:
  name: ztp-policy-common
---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-policy-group
---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-policy-site
---
apiVersion: v1
kind: Namespace
metadata:
  name: ztp-policy-cluster
