---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-vseextras
  namespace: ztp-policy-common
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-catalogs
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: CatalogSource
                metadata:
                  name: certified-operators
                  namespace: openshift-marketplace
                spec:
                  displayName: Telco 4.14 Certified
                  image: altiostar-registry.cars.lab:5000/redhat/certified-operator-index:v4.13
                  publisher: Red Hat
                  sourceType: grpc
                  updateStrategy:
                    registryPoll:
                      interval: 10m0s                  
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-vseextras
  namespace: ztp-policy-common
placementRef:
  name: placement-policy-vseextras
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-vseextras
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-vseextras
  namespace: ztp-policy-common
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: vseextras, operator: In, values: ["true"]}
